const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const path=require('path');const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.FIGGY_BROWSER||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:440,height:1100},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.resolve('Figgy/Preview/Figgy-Preview.html'));
 await page.waitForFunction(()=>document.querySelectorAll('#cards .pack').length===3);
 await page.screenshot({path:'Figgy/Preview/Explore.png',fullPage:true});
 await page.getByRole('button',{name:'Estudos',exact:true}).click();
 if(await page.locator('#cards .pack').count()!==1)throw Error('Category filter failed');
 await page.getByRole('button',{name:'Todos',exact:true}).click();
 await page.locator('[data-pack=mood]').click();await page.getByRole('button',{name:'Baixar pack grátis'}).click();
 await page.locator('[data-nav=library]').click();
 if(await page.locator('[data-library]').count()!==1)throw Error('Install failed');
 await page.locator('[data-library]').click();await page.getByRole('button',{name:'iPhone',exact:true}).click();
 if(!await page.locator('#info').isVisible())throw Error('Native explanation missing');
 await page.getByRole('button',{name:'Entendi',exact:true}).click();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Baixar / compartilhar .figpack'}).click();
 const download=await downloadPromise;await download.saveAs('Figgy/Preview/test-export.figpack');
 await page.locator('[data-nav=create]').click();
 await page.locator('#photo-input').setInputFiles('Figgy/Resources/Catalog/study-1.png');
 await page.waitForFunction(()=>editor.image!==null);
 await page.locator('#caption').fill('EU CONSIGO');await page.locator('[data-bg="#BDE9D1"]').click();
 const changed=await page.evaluate(()=>({text:editor.text,bg:editor.background}));
 if(changed.text!=='EU CONSIGO'||changed.bg!=='#BDE9D1')throw Error('Editor controls failed');
 await page.screenshot({path:'Figgy/Preview/Editor.png',fullPage:true});
 await page.getByRole('button',{name:/Salvar figurinha/}).click();
 await page.waitForFunction(()=>page==='library');
 if(await page.locator('[data-library]').count()!==2)throw Error('Save to pack failed');
 await page.screenshot({path:'Figgy/Preview/Library.png',fullPage:true});
 await page.locator('#pack-input').setInputFiles('Figgy/Resources/Example.figpack');
 await page.waitForFunction(()=>packs.length===3);
 await page.reload();await page.locator('[data-nav=library]').click();
 if(await page.locator('[data-library]').count()!==3)throw Error('Persistence failed');
 await page.setViewportSize({width:320,height:900});await page.locator('[data-nav=create]').click();
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile horizontal overflow');
 if(errors.length)throw Error('Browser errors: '+errors.join(', '));
 console.log('PASS: browse/filter/install, native handoff explanation, pack ZIP export/import, image editor, save, persistence, 320px layout; no browser runtime errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
